version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    restart: always
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03,es04
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    restart: always
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03,es04
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data02:/usr/share/elasticsearch/data
    networks:
      - elastic
    depends_on:
      - es01
    
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    restart: always
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02,es04
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data03:/usr/share/elasticsearch/data
    networks:
      - elastic
    depends_on:
      - es01

  es04:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    restart: always
    container_name: es04
    environment:
      - node.name=es04
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02,es04
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data04:/usr/share/elasticsearch/data
    networks:
      - elastic
    depends_on:
      - es01


  # logstash:
  #   image: docker.elastic.co/logstash/logstash:7.5.0
  #   container_name: logstash
  #   restart: always
  #   environment:
  #     - xpack.monitoring.elasticsearch.hosts=http://es01:9200
  #     - "LS_JAVA_OPTS=-Xmx512m -Xms512m"
  #   volumes:
  #     - logstash_data:/usr/share/logstash/data
  #     - /data/docker/docker-elk/pipeline/:/usr/share/logstash/pipeline/
  #   ports:
  #     - '5044:5044'
  #   networks:
  #     - elastic 
  #   entrypoint:
  #     - logstash
  #     - -f
  #     - logstash.conf

# https://www.elastic.co/guide/cn/kibana/current/docker.html
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    restart: always
    container_name: kibana
    environment:
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - '5601:5601'
    networks:
      - elastic

volumes:
  es_data01:
    driver: local
  es_data02:
    driver: local
  es_data03:
    driver: local
  es_data04:
    driver: local
#  logstash_data:
#    driver: local

networks:
  elastic:
    driver: bridge